import { TutorialStep } from "../types/tutorial";

  export const TUTORIAL_STEPS: TutorialStep[] = [
    {
      id: 1,
      title: 'Welcome to Rove',
      description: 'Rove helps protect you by monitoring your surroundings and alerting your trusted contacts in case of danger. Let us show you how it works.',
      screen: 'LiveStream',
      action: 'navigate',
      navigationTarget: 'Settings',
    },
    {
      id: 2,
      title: 'Access Settings',
      description: 'First, let\'s set up your trusted contacts. Tap the Settings icon at the bottom to continue.',
      screen: 'LiveStream',
      highlightElement: 'settings-tab',
      highlightType: 'circle',
      action: 'navigate',
      navigationTarget: 'Settings',
      isNavigationStep: true,
    },
    {
      id: 3,
      title: 'Add Responders',
      description: 'Now tap on "Responders" to add your trusted contacts who will be notified during emergencies.',
      screen: 'Settings',
      highlightElement: 'responders-item',
      highlightType: 'rounded',
      action: 'navigate',
      navigationTarget: 'TrustedContacts',
      isNavigationStep: true,
    },
    {
      id: 4,
      title: 'Add Your First Contact',
      description: 'Add at least one trusted contact who will receive alerts when you\'re in danger. Tap "Add Contact" to get started.',
      screen: 'TrustedContacts',
      highlightElement: 'add-contact-button',
      highlightType: 'rounded',
      action: 'interact',
    },
    {
      id: 5,
      title: 'Great! You\'re All Set',
      description: 'Perfect! You now have trusted contacts set up. Let\'s go back to the LiveStream to learn how to use Rove\'s protection features.',
      screen: 'TrustedContacts',
      action: 'navigate',
      navigationTarget: 'LiveStream',
    },
    {
      id: 6,
      title: 'Your Safety Dashboard',
      description: 'This is your main safety interface. The red button starts emergency streaming to your contacts.',
      screen: 'LiveStream',
      highlightElement: 'livestream-button',
      highlightType: 'circle',
      action: 'complete',
    },
  ];