
export const RouteNames = {
  AuthRoutes: {
    SplashScreen: 'SplashScreen',
    LoginScreen: 'LoginScreen',
    OnBoardingScreen: 'OnBoardingScreen',
    ReadBeforeUse: 'ReadBeforeUse',
    ForgotPasswordScreen: 'ForgotPasswordScreen',
    OtpScreen: 'OtpScreen',
    RegisterScreen: 'RegisterScreen',
    Preferences: 'Preferences',
  },
  HomeRoutes: {
    TabStack: 'TabStack',
    LiveStream: 'LiveStream',
    HomeScreen: 'HomeScreen',
    NavigationScreen: 'NavigationScreen',
    Settings: 'Settings',
    EditProfileScreen: 'EditProfileScreen',
    SubscriptionScreen: 'SubscriptionScreen',
    AddContacts: 'AddContacts',
    EditPreferences: 'EditPreferences',
    TermsAndPolicy: 'TermsAndPolicy',
    FAQ: 'FAQ',
    HelpCenter: 'HelpCenter',
    Footages: 'Footages',
    FootageDetails: 'FootageDetails',
    Videos: 'Videos',
    HeartRateMonitor: "HeartRateMonitor",
    Premium: 'Premium',
    PasscodeSettings: 'PasscodeSettings',
    TrustedContacts: 'TrustedContacts',
    HowToUse: 'HowToUse',
    SafeWord: 'SafeWord',
    SafeWordTraining: 'SafeWordTraining',
    EditContact: 'EditContact',
  },
};
